[http]
port = 8080

[https]
port = 8443
domains = ["localhost"]
cert_mode = "self_signed"
letsencrypt_prod = false

[dns]
port = 5300
default_soa = "dns1.irohdns.example hostmaster.irohdns.example 0 10800 3600 604800 3600"
default_ttl = 900
origin = "irohdns.example."
additional_origins = ["."]
ipv4_addr = "127.0.0.1"
