[https]
port = 443
domain = "localhost"
cert_mode = "lets_encrypt"
letsencrypt_prod = false

[dns]
port = 53
default_soa = "dns1.irohdns.example hostmaster.irohdns.example 0 10800 3600 604800 3600"
default_ttl = 30
origin = "irohdns.example."
additional_origins = ["iroh."]
ipv4_addr = "5.75.181.3"
ns_name = "ns1.iroh.link"
